[package]
name = "files"
version = "0.1.0"
authors = ["Dov Kruger <Dov.Kruger@stevens.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "vec3d"
path = "vec3d.rs"
